ZOMBIE:
    respawn: 1000
    conf:
        - '2000/F:SPEED,1;JUMP,2;REGENERATION,0'
        - '1000/F:FIRE_RESISTANCE,1;SPEED,3;JUMP,4;REGENERATION,0'
        - '500/@:SPEED,3;JUMP,4;INVISIBILITY,0'
        - '3250:SPEED,1;'
        - '3250/1:SPEED,1;'

DROWNED:
    respawn: 1000
    conf:
        - '2000:SPEED,1;JUMP,2;REGENERATION,0'
        - '1000:FIRE_RESISTANCE,1;SPEED,3;JUMP,4;REGENERATION,0'
        - '500/@:SPEED,3;JUMP,4;INVISIBILITY,0'
        - '3250:SPEED,1;'
        - '3250/1:SPEED,1;'

HUSK:
    respawn: 1000
    conf:
        - '2000/F:SPEED,1;JUMP,2;REGENERATION,0'
        - '1000/F:SPEED,3;JUMP,4;REGENERATION,0'
        - '500/@:SPEED,3;JUMP,4;INVISIBILITY,0'
        - '3250:SPEED,1;'
        - '3250/1:SPEED,1;'

CREEPER:
    respawn: 1000
    conf:
        - '5000:SPEED,0;'
        - '1500/F:;'
        - '2000:SPEED,3;JUMP,3'
        - '1000/1:SPEED,2;JUMP,3'
        - '500/@1:SPEED,0;JUMP,1;POISON,3;REGENERATION,2;INVISIBILITY,0'

SKELETON:
    respawn: 1000
    conf:
        - '2000:SPEED,1;JUMP,2;REGENERATION,0'
        - '1000/F:FIRE_RESISTANCE,1;SPEED,3;JUMP,4;REGENERATION,0'
        - '500/@:SPEED,3;JUMP,4;INVISIBILITY,0'
        - '3250:SPEED,1;'
        - '3250/1:SPEED,1;'

WITHER_SKELETON:
    respawn: 1000
    conf:
        - '2000:SPEED,1;JUMP,2;REGENERATION,0'
        - '1000/F:SPEED,3;JUMP,4;REGENERATION,0'
        - '500/@:SPEED,3;JUMP,4;INVISIBILITY,0'
        - '3250:SPEED,1;'
        - '3250/1:SPEED,1;'

STRAY:
    respawn: 1000
    conf:
        - '2000:SPEED,1;JUMP,2;REGENERATION,0'
        - '1000:FIRE_RESISTANCE,1;SPEED,3;JUMP,4;REGENERATION,0'
        - '500/@:SPEED,3;JUMP,4;INVISIBILITY,0'
        - '3250:SPEED,1;'
        - '3250/1:SPEED,1;'

SPIDER:
    respawn: 1000
    conf:
        - '2000:SPEED,1;JUMP,2;REGENERATION,1'
        - '1000:SPEED,3;JUMP,4;REGENERATION,2'
        - '500/@:SPEED,3;JUMP,4;INVISIBILITY,0'
        - '10000:SPEED,1;REGENERATION,0'

CAVE_SPIDER:
    respawn: 1000
    conf:
        - '2000:SPEED,1;JUMP,2;REGENERATION,1'
        - '1000:SPEED,3;JUMP,4;REGENERATION,2'
        - '500/@:SPEED,3;JUMP,4;INVISIBILITY,0'
        - '10000:SPEED,1;REGENERATION,0'

HOGLIN:
    respawn: 1000
    conf:
        - '2000:SPEED,1;JUMP,1;REGENERATION,0;HEALTH_BOOST,5;'
        - '1000:SPEED,3;JUMP,3;REGENERATION,1;INCREASE_DAMAGE,0;HEALTH_BOOST,5;'
        - '10000:SPEED,0;JUMP,0;REGENERATION,0;'

ZOGLIN:
    respawn: 1000
    conf:
        - '2000:SPEED,1;JUMP,1;REGENERATION,0;HEALTH_BOOST,5;'
        - '1000:SPEED,3;JUMP,3;REGENERATION,1;INCREASE_DAMAGE,0;HEALTH_BOOST,5;'
        - '10000:SPEED,0;JUMP,0;REGENERATION,0;'

PIGLIN:
    respawn: 1000
    conf:
        - '2000:SPEED,1;JUMP,1;REGENERATION,0;HEALTH_BOOST,5;'
        - '1000:SPEED,3;JUMP,3;REGENERATION,1;INCREASE_DAMAGE,0;HEALTH_BOOST,5;'
        - '10000:SPEED,0;JUMP,0;REGENERATION,0;'

PIGLIN_BRUTE:
    respawn: 1000
    conf:
        - '2000:SPEED,1;JUMP,1;REGENERATION,0;HEALTH_BOOST,5;'
        - '1000:SPEED,3;JUMP,3;REGENERATION,1;INCREASE_DAMAGE,0;HEALTH_BOOST,5;'
        - '10000:SPEED,0;JUMP,0;REGENERATION,0;'

ZOMBIFIED_PIGLIN:
    respawn: 1000
    conf:
        - '2000:SPEED,1;JUMP,1;REGENERATION,0;HEALTH_BOOST,5;'
        - '1000:SPEED,3;JUMP,3;REGENERATION,1;INCREASE_DAMAGE,0;HEALTH_BOOST,5;'
        - '3000/F:SPEED,0;'
        - '10000:SPEED,0;JUMP,0;REGENERATION,0;'

PHANTOM:
    respawn: 1000
    conf:
        - '2000:SPEED,1;REGENERATION,0;HEALTH_BOOST,5;'
        - '10000:SPEED,0;REGENERATION,0;'

EVOKER: []

PILLAGER: []

VINDICATOR: []

RAVAGER: []

VEX: []

ENDERMAN: []

WITCH:
    respawn: 1000
    conf:
        - '2000:SPEED,1;JUMP,2;REGENERATION,1'
        - '1000:SPEED,3;JUMP,4;REGENERATION,2'
        - '500/@:SPEED,3;JUMP,4;INVISIBILITY,0'
        - '7500:SPEED,1;REGENERATION,0'

BLAZE:
    respawn: 1000
    conf:
        - '2000:SPEED,1;JUMP,1;REGENERATION,0;HEALTH_BOOST,5;'
        - '1000:SPEED,3;JUMP,3;REGENERATION,1;INCREASE_DAMAGE,0;HEALTH_BOOST,5;'
        - '10000:SPEED,0;JUMP,0;REGENERATION,0;'

GHAST:
    respawn: 1000
    conf:
        - '7000:SPEED,5;JUMP,5;REGENERATION,2;HEALTH_BOOST,2;'
        - '1500:SPEED,7;JUMP,7;REGENERATION,2;ABSORPTION,1;HEALTH_BOOST,2;'
        - '500/@:SPEED,5;JUMP,5;REGENERATION,0;HEALTH_BOOST,1;INVISIBILITY,0'

GUARDIAN:
    respawn: 1000
    conf:
        - '2000:SPEED,1;JUMP,1;REGENERATION,0;HEALTH_BOOST,5;'
        - '1000:SPEED,3;JUMP,3;REGENERATION,1;INCREASE_DAMAGE,0;HEALTH_BOOST,5;'
        - '10000:SPEED,0;JUMP,0;REGENERATION,0;'

ELDER_GUARDIAN:
    respawn: 1000
    conf:
        - '2000:SPEED,1;JUMP,1;REGENERATION,0;HEALTH_BOOST,5;'
        - '1000:SPEED,3;JUMP,3;REGENERATION,1;INCREASE_DAMAGE,0;HEALTH_BOOST,5;'
        - '10000:SPEED,0;JUMP,0;REGENERATION,0;'

SILVERFISH:
    respawn: 1000
    conf:
        - '2000:SPEED,1;JUMP,1;REGENERATION,0;HEALTH_BOOST,5;'
        - '1000:SPEED,3;JUMP,3;REGENERATION,1;INCREASE_DAMAGE,0;HEALTH_BOOST,5;'
        - '10000:SPEED,0;JUMP,0;REGENERATION,0;'

ENDERMITE: []

SLIME: []

ENDER_DRAGON:
    respawn: 5000
    conf:
        - '10000:FIRE_RESISTANCE,1;SPEED,9;REGENERATION,0;INCREASE_DAMAGE,2;ABSORPTION,40;HEALTH_BOOST,40;'

WITHER:
    respawn: 3000
    conf:
        - '7000:FIRE_RESISTANCE,1;SPEED,5;REGENERATION,0;INCREASE_DAMAGE,1;ABSORPTION,10;HEALTH_BOOST,10;HEAL,3;'
        - '10000:FIRE_RESISTANCE,1;SPEED,7;REGENERATION,0;INCREASE_DAMAGE,3;DAMAGE_RESISTANCE,0;ABSORPTION,20;HEALTH_BOOST,20;'

IRON_GOLEM:
    respawn: 0
    conf:
        - '1000/F:REGENERATION,2;'
        - '10000:REGENERATION,0;'

SNOWMAN:
    respawn: 0
    conf:
        - '1000/F:REGENERATION,2;'

