name: ${project.name}
version: ${project.version}
main: ${project.groupId}.P
api-version: 1.13
description: ${project.description}
author: thatguy

commands:
  potionmon:
    description: "reload config"
    permission: potionmon.reload
    usage: "/potionmon reload"

permissions:
  potionmon.reload:
    description: Gives access to reload command
    default: op

